export default function Page() {
  return (
    <div>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
      <h1>AboutUs</h1>
    </div>
  );
}
